### ISSUE TITLE
Add Issue Checklist

### ISSUE THREAD

**Issue by jmarsh24** [nerdgeschoss/pull-request#26]
This PR introduced the following checklist to be written into every new Issue when using this gem. The developer and Peer reviewer shall check these boxes **BEFORE** it makes it into review.

**How to test this:**
_fill this out, adding a link to the feature in the review app and a description how to test_

**Developer Checklist**
- [ ] I reviewed my own code in the code changes tab.
- [ ] There is a test representing the issue I tried to fix or the feature I developed.
- [ ] All files in the PR should actually be there and match the specified issue. I checked the code changes tab that I didn't accidentally committed unrelated files.
- [ ] I tested the feature on a review app.
- [ ] All user-facing strings are translated with approved copy.
- [ ] I added a deeplink to a review app for others to test this feature.
- [ ] The PR is not in draft anymore, the issue is moved to the correct status.
- [ ] I added a link and description of the feature built and noted which areas to focus QA on.

**Peer Review Checklist**
- [ ] I checked the original issues for any comments there.
- [ ] I tested the feature on a review app.
- [ ] I checked that the implemented feature is fulfilling the acceptance criteria of the issue.
- [ ] I compared the final solution with the corresponding Figma file.

**Comment by Adeynack** [comment]
@jmarsh24 : What's the goal of this issue? Was it created in the right project?

**Comment by jmarsh24** [comment]
@Adeynack The goal was that anytime a user creates a PR, it already has this checklist attached to the issue.

I spoke with @JensRavens briefly and I think we actually want to integrate a template instead of the current method.

**Comment by JensRavens** [comment]
`pr` already supports using PR templates from github, so we just need to add those to the corresponding projects.
